config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get '/license-renewal', to: 'license_renewal#index'
  resources :garages
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
authenticate :user, lambda { |u| u.admin? } do
  mount Sidekiq::Web => '/sidekiq'

  namespace :madmin do
  end
end

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/garage.rb
class Garage < ApplicationRecord
  extend FriendlyId
  friendly_id :license_plate, use: :slugged
  validates_uniqueness_of :license_plate
  belongs_to :user , optional: true
end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController
  before_action :set_garage, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :current_user_garage, only:[:show]

  # GET /garages or /garages.json
  def index
    @garages = Garage.all
  end

  # GET /garages/1 or /garages/1.json
  def show
  end

  # GET /garages/new
  def new
    @garage = current_user.garages.build
  end

  # GET /garages/1/edit
  def edit
  end

  # POST /garages or /garages.json
  def create
    @garage = current_user.garages.build(garage_params)

    respond_to do |format|
      if @garage.save
        format.html { redirect_to @garage, notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @garage }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @garage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /garages/1 or /garages/1.json
  def update
    respond_to do |format|
      if @garage.update(garage_params)
        format.html { redirect_to @garage, notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @garage }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @garage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /garages/1 or /garages/1.json
  def destroy
    @garage.destroy
    respond_to do |format|
      format.html { redirect_to garages_url, notice: "Car was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garage
      @garage = Garage.friendly.find(params[:id])
    end

    def correct_user
    @garage = current_user.garages.find_by(params[:friendly])
        redirect_to garages_path, notice: "Not authorised to edit" if @garage.nil?
  end
  # check if  cars belongs to the correct user - current user
    def current_user_garage
      if user_signed_in?
        @garages = current_user.garages.order("created_at DESC")
     end
   end

    # Only allow a list of trusted parameters through.
    def garage_params
      params.require(:garage).permit(:make, :model, :license_plate, :year)
    end
end

app/helpers/garages_helper.rb
module GaragesHelper
end

app/views/garages/_form.html.erb
<div class="container-fluid">
  <div class="col-lg-12">
    <%= form_with(model: garage, local: true) do |form| %>
    <% if garage.errors.any? %>
    <%=render 'garages/templates/error'%>
    <% end %>

    <div class="form-group">
      <%#= form.select :year, {}, {prompt:"Select Car Year"}, class: 'form-control',  name:"car-years" , id:"car-years" %>
      <%= form.text_field :year, class: 'form-control upcase' , placeholder:"Year Model"%>

    </div>

    <div class="form-group">
      <%#= form.select :make, {},{prompt:"Select Car Make"}, class: 'form-control',  name:"car-makes" , id:"car-makes" %>
      <%= form.text_field :make, class: 'form-control upcase' , placeholder:"Car Make"%>

    </div>

    <div class="form-group">
      <%#= form.select :model, {},{prompt:"Select Car Model"}, class: 'form-control',  name:"car-models" , id:"car-models" %>
      <%= form.text_field :model, class: 'form-control upcase' , placeholder:"Car Model"%>

    </div>

    <div class="form-group">
      <%= form.text_field :license_plate, class: 'form-control upcase' , placeholder:"License Plate Number" ,maxlength: 10, size: 10, required: :required%>
    </div>

    <div class="form-group">
      <% if garage.persisted? %>
      <div class="float-right">
        <%= link_to garage, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' } do %>
        <i class="fas fa-trash"></i>
        <%end%>
      </div>
      <% end %>

      <%= form.button(type: "submit", class: "btn btn-secondary text-light" , data: {disable_with:"<i class='fa fa-spinner fa-spin'></i> Saving..." .html_safe }) do %>
      <i class="fas fa-save"></i> SAVE
      <% end %>

      <% if garage.persisted? %>
      <%= link_to "Cancel", garage, class: "btn btn-link" %>
      <% else %>
      <%= link_to "Cancel", garages_path, class: "btn btn-link" %>
      <% end %>
    </div>
    <% end %>
  </div>
</div>

app/views/garages/edit.html.erb
<div class="container-fluid mt-3">
  <ol class="breadcrumb mb-4">
      <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
      <li class="breadcrumb-item active">Ticking & License Portal / Edit</li>
  </ol>

    <div class="card mb-12">
    <div class="card-body width">
     <h4 class="bg-light text-dark p-2"> <i class="fas fa-edit"></i> Edit Car</h4>
    <hr>
    <%= render 'form', garage: @garage %>

    </div>

    </div>
</div>

app/views/garages/index.html.erb
<div class="container-fluid mt-3">
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
    <li class="breadcrumb-item active">Ticking & License Portal / My Garage</li>
  </ol>
  <div class="card mb-12">
    <div class="card-body width">
      <div class="row">
        <div class="col-sm-6">
          <h4> <i class="fas fa-car"></i> My Garage</h4>
        </div>

        <div class="col-sm-6 text-right">
          <%= link_to new_garage_path, class: 'btn btn-secondary text-light' do %>
          <i class="fas fa-plus-square"></i> ADD CAR
          <% end %>
        </div>
      </div>
      <br>
      <%if current_user.garages.empty?%>
      <hr>
      <p class="text-center bg-light p-2 text-dark lead"><i class="far fa-folder-open"></i> <br> <small>Nothing has been added yet! </small></p>
      <%else%>
      <%=render 'garages/templates/content' %>
      <% end %>
    </div>
  </div>

app/views/garages/new.html.erb
<div class="container-fluid mt-3">
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
    <li class="breadcrumb-item active">Ticking & License Portal / Add Car</li>
  </ol>
  <div class="card mb-12">
    <div class="card-body width">
      <h4 class="bg-light text-dark p-2"> <i class="fas fa-car"></i> Add Car</h4>
      <hr>
      <%= render 'form', garage: @garage %>
    </div>
  </div>
</div>

app/views/garages/show.html.erb
<div class="container-fluid mt-3">
  <ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
    <li class="breadcrumb-item active">Ticking & License Portal / Car Details</li>
  </ol>
  <div class="card mb-4">
    <div class="card-body">
      <h4 class="bg-light text-dark p-2"><i class="fas fa-car"></i> Car Details</h4>
      <hr>
      <%if current_user && @garage.user == current_user%>
        <dl class="dl-horizontal">
          <dt>Make:</dt>
          <dd><%= @garage.make.upcase %></dd>
          <dt>Model:</dt>
          <dd><%= @garage.model.upcase %></dd>

          <dt>License plate:</dt>
          <dd><%= @garage.license_plate.upcase %></dd>

          <dt>Year:</dt>
          <dd><%= @garage.year %></dd>
      <%end%>
      </dl>
    </div>
  </div>
  <div class="page-header">
    <%= link_to garages_path, class: 'btn btn-warning text-dark' do %>
    <i class="fas fa-list"></i> View All Cars
    <% end %>
    <%= link_to edit_garage_path(@garage), class: 'btn btn-secondary text-light' do %>
    <i class="fas fa-edit"></i>  Edit
    <% end %>
  </div>

</div>